name: Generate snake animation

on:
  schedule: # execute every 1 hours
    - cron: "* */1 * * *"

  workflow_dispatch:

  push:
    branches:
    - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.com/rafaelats14 }}
          outputs: dist/snake.svg


      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ 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 }}
